routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/formulir', function () {
    return view('formulir');
});

Route::post('/kirim', 'Controller@kirimform' );

// Route::get('ID/{id}',function($id){ echo 'isi ID adalah : '.$id; }); 
 

// Route::get('ID/{id}/{nama}',function($id,$nama){ echo 'NRP : '.$id .' nama : ' .$nama ; }); 


Route::get('ID/{id}/{nama}/{alamat?}',function($id,$nama,$alamat='kejawan putih'){ echo 'NRP : '.$id .' nama : ' .$nama .'alamat : ' .$alamat; }); 

Route::get('/formget', function () {
return view('formget');
});


Route::get('/formpost', function () {
return view('formpost');
});

Route::get('/abc', function () {
return view('abc');
});

Route::match(['get', 'post'],'/submitPost', 'Controller@submitForm');

Route::resource('mhs','mhsController');

Route::resource('mhs','mhsControllerAll');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/mhs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class mhs extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\Input;


class Controller extends BaseController
{
    
    public function kirimform()
    {
    	$usr = Input :: get ('username');
    	$addr = Input :: get ('alamat');
    	$pwd = Input :: get ('password');
    	return 'Nama : '.$usr.'<br/> Alamat : '.$addr.'<br/> Password : '.$pwd;
    }
    public function submitForm()
    {
    	$nama = Input :: get ('nama');
    	$email = Input :: get ('email');

    	return view('formpost');
    }

}

app/Http/Controllers/mhsController.php
<?php

namespace App\Http\Controllers;

use App\mhs;

use Illuminate\Http\Request;

class mhsController extends Controller
{
    function index()
	{        $data['mhs'] = mhs::all();        // Memanggil semua data dari tabel mhs dan disimpan dalam array dengan nama index mhs
	         return view('mhs.index',$data);    } 	// Memanggil view dan memparsing data mhs untuk ditampilkan pada halaman view

}

app/Http/Controllers/mhsControllerAll.php
<?php

namespace App\Http\Controllers;

use App\mhs;

use Illuminate\Http\Request;

use App\Http\Requests\mhs\StoreRequest;
use App\Http\Requests\mhs\UpdateRequest;


class mhsControllerAll extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {      
        // 
        $data['mhs'] = mhs::all();        
        return view('mhs.index',$data);    
    } 
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
         return view('mhs.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        //
        $m = new mhs();        
        $m->nrp = $request->nrp;        
        $m->nama = $request->nama;      
        $m->alamat = $request->alamat;        
        $m->save();        
        return redirect()->route('mhs.index')->with('alert-success', 'Data Berhasil Disimpan.');    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $m = mhs::findOrFail($id); 
        return view('mhs.edit', compact('m')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        //
        $m = mhs::findOrFail($id);      
        $m->nrp = $request->nrp;        
        $m->nama = $request->nama;        
        $m->alamat = $request->alamat;        
        $m->save();        
        return redirect()->route('mhs.index')->with('alert-success', 'Data Berhasil Diubah.');    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $m = mhs::findOrFail($id);       
        $m->delete();
        return redirect()->route('mhs.index')->with('alert-success', 'Data Berhasil Dihapus.');   
    }
}

resources/views/abc.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" 
        content="width=device-width, initial-scale=1">
 <link rel ="stylesheet" href="css/bootstrap.min.css">
 <script src ="js/jquery.min.js"></script>
 <script src ="js/bootstrap.min.js"></script>
  <style>
  .modal-header, h4, .close {
      background-color: #5cb85c;
      color:white !important;
      text-align: center;
      font-size: 30px;
  }
  .modal-footer {
      background-color: #f9f9f9;
  }
  </style>
</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span> <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
     <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
     <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<body>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog"> 
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
         <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form role="form" action="/login" method="post">
            <div class="form-group">
            <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="text" class="form-control" id="usrname" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="text" class="form-control" id="psw" placeholder="Enter password">
            </div>
            <div class="checkbox">
              <label><input type="checkbox" value="" checked>Remember me</label>
            </div>
              <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
 <div class="modal-footer">
         
          <p>Not a member? <a href="#">Sign Up</a></p>
          <p>Forgot <a href="#">Password?</a></p>
        </div>
      </div>
      
    </div>
  </div> 
<script>
$(document).ready(function(){
        $("#myModal").modal({
backdrop: 'static'
});
});
</script>
</body>
</html>

resources/views/formget.blade.php
<!DOCTYPE html>
<html>
<head>
		<form method="GET" action="">
			Nama:: <input type="text" name="nama"><br>
			Email:: <input type="text" name="email"><br>
					<input type="submit" name="submit" value="Submit">
		</form>
</head>
<body>

</body>
</html>




<?php
if ($_GET)
{
echo 'Nama: ' . $_GET['nama'];
echo '<br>';
echo 'Email: ' . $_GET['email'];
}
?>

</body>
</html>

resources/views/formpost.blade.php
<html>
<body>
	<!-- <form method="POST" action="/submitPost"> -->
		<form method="POST" action="/submitPost" >
		<!-- <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">  -->
		{{ csrf_field()}}

		<!-- {{ Form::open(['url' => '/submitPost']) }}  -->

		Nama:: <input type="text" name="nama"><br>
		Email:: <input type="text" name="email"><br>
		<input type="submit" name="submit" value="Submit">
</form>

<?php
	if ($_POST)
	{
		echo 'Nama: ' . $_POST['nama'];
		echo '<br>';
		echo 'Email: ' . $_POST['email'];
	}
?>
</body>
</html>

resources/views/formulir.blade.php
<p>This is my body content.</p>
    <hr>
    {{ Form::open(['url' => '/kirim' ]) }}
    {!! Form::label('nama', 'Nama') !!} 
    {!! Form::text('username')  !!}<br>
    {!! Form::textarea('alamat')  !!}<br>
    {!! Form::password('password') !!}<br>
    {!! Form::hidden('id') !!}<br>
    {!! Form::submit('Submit') !!} <br>
    {!! Form::close() !!}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Akademik</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	@yield('content')
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/mhs/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>Akademik:Tabel Mahasiwa</h3>
			<div class="panel panel-default"><div class="panel-body">
				<form action="{{route('mhs.store')}}" method="post">
						{{csrf_field()}}
						<div class="form-group{{ $errors->has('nrp') ? ' has-error' : '' }}">
							<input type="text" name="nrp" class="form-control" placeholder="Nrp">
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
							<input type="text" name="nama" class="form-control" placeholder="Nama">
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('alamat') ? ' has-error' : '' }}">
							<input type="text" name="alamat" class="form-control" placeholder="Alamat">
							{!! $errors->first('alamat', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group"> 
							<input type="submit" class="btn btn-primary" value="Simpan"></div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/mhs/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">	
	<div class="row">
		<div class="col-md-12">
		<h3>Tabel Mahasiswa Edit</h3>
			<div class="panel panel-default">
				<div class="panel-body">
					<form action="{{route('mhs.update', $m->id)}}" method="post">
 						<input name="_method" type="hidden" value="PATCH">
 						{{csrf_field()}}
 							<div class="form-group{{ $errors->has('nrp') ? ' has-error' : '' }}">
 								<input type="text" name="nrp" class="form-control" placeholder="Nrp" value="{{$m->nrp}}">
 								{!! $errors->first('nrp', '<p class="help-block">:message</p>') !!}
 							</div>
							<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
 								<input type="text" name="nama" class="form-control" placeholder="Nama" value="{{$m->nama}}">
 								{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
 							</div>
 							<div class="form-group{{ $errors->has('alamat') ? ' has-error' : '' }}">
								 <input type="text" name="alamat" class="form-control" placeholder="Alamat" value="{{$m->alamat}}">
								 {!! $errors->first('alamat', '<p class="help-block">:message</p>') !!}
							</div>
 							<div class="form-group">
								<input type="submit" class="btn btn-primary" value="Simpan">
							</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/mhs/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>Tabel Mahasiswa</h3>
				<div class="panel panel-default">
					<div class="panel-body">
						@if(Session::has('alert-success'))
					    	<div class="alert alert-success">
								{{ Session::get('alert-success') }}
							</div>
						@endif
							<a href="{{route('mhs.create')}}" class="btn btn-info pull-right">Tambah Data</a><br><br>
								<table class="table table-striped">
									<tr><th>NO</th><th>NRP</th><th>Nama</th><th>Alamat</th><th>Action</th></tr>
									<?php $no=1; ?>
									@foreach($mhs as $m)
									<tr><td>{{$no++}}</td><td>{{$m->nrp}}</td><td>{{$m->nama}}</td><td>{{$m->alamat}}</td><td>
									<form method="POST" action="{{ route('mhs.destroy', $m->id) }}" accept-charset="UTF-8">
								 		<input name="_method" type="hidden" value="DELETE">
								 		<input name="_token" type="hidden" value="{{ csrf_token() }}">
								 		<a href="{{route('mhs.edit', $m->id)}}" class="btn btn-primary">Edit</a>
								 		<input type="submit" class="btn btn-danger" 
								   			onclick="return confirm('Anda yakin akan menghapus data ?');" value="Delete">
									</form></td></tr>
									@endforeach
								</table>
								</div>
					</div>
				</div>
		</div>
</div>
@endsection